default: &default
  adapter: postgresql
  encoding: utf8
  min_messages: warning
  pool: <%= Integer(ENV.fetch("DB_POOL", 5)) %>
  reaping_frequency: <%= Integer(ENV.fetch("DB_REAPING_FREQUENCY", 10)) %>
  timeout: 5000
  host: localhost
  username: postgres
  password:

development:
  <<: *default
  database: Valkyrie_gem_development
  url: <%= ENV['DATABASE_URL'] %>

test:
  <<: *default
  database: Valkyrie_gem_test
  port: <%= ENV["POSTGRES_PORT"] || 5433 %>
